### ISSUE TITLE
ffmgeg

### ISSUE THREAD

**Issue by forsomefun** [beaston02/ChaturbateRecorder#15]
Does the conversion and encoding built into this python code use this program (ffmgeg)

I found the script to convert the files to MP4 
- For some reason, windows don't seem to play nice with the files generated by camsites.  They need some work to operate smoothly 

My question is what would be the best way to integrate this with the code. For example the post processing commands.

**Comment by forsomefun** [comment]
use strict';
var Promise = require('bluebird');
var fs = Promise.promisifyAll(require('fs'));
var S = require('string');
var yaml = require('js-yaml');
var colors = require('colors');
var childProcess = require('child_process');
var mkdirp = require('mkdirp');
var path = require('path');
var moment = require('moment');
var _ = require('underscore');

function getCurrentDateTime() {
  return moment().format('YYYY-MM-DDTHHmmss'); // The only true way of writing out dates and times, ISO 8601
};

function printMsg(msg) {
  console.log(colors.blue('[' + getCurrentDateTime() + ']'), msg);
}

function printErrorMsg(msg) {
  console.log(colors.blue('[' + getCurrentDateTime() + ']'), colors.red('[ERROR]'), msg);
}

function getTimestamp() {
  return Math.floor(new Date().getTime() / 1000);
}

var startTs;
var config = yaml.safeLoad(fs.readFileSync('convert.yml', 'utf8'));

config.srcDirectory = path.resolve(config.srcDirectory);
config.dstDirectory = path.resolve(config.dstDirectory);

mkdirp.sync(config.srcDirectory);
mkdirp.sync(config.dstDirectory);

function getFiles() {
  return fs
    .readdirAsync(config.srcDirectory)
    .then(function(files) {
      return _.filter(files, function(file) {
        return S(file).endsWith('.ts') || S(file).endsWith('.flv');
      });
    });
}

function convertFile(srcFile) {
  var dstFile;
  var srcFile;
  var spawnArguments;

  if (S(srcFile).endsWith('.ts')) {
    dstFile = S(srcFile).chompRight('ts').s + 'mp4';

    spawnArguments = [
      '-i',
      config.srcDirectory + '/' + srcFile,
      '-y',
      '-hide_banner',
      '-loglevel',
      'panic',
      '-c:v',
      'copy',
      '-c:a',
      'copy',
      '-bsf:a',
      'aac_adtstoasc',
      '-copyts',
      config.srcDirectory + '/' + dstFile
    ];
  }

  if (S(srcFile).endsWith('.flv')) {
    dstFile = S(srcFile).chompRight('flv').s + 'mp4';

    spawnArguments = [
      '-i',
      config.srcDirectory + '/' + srcFile,
      '-y',
      '-hide_banner',
      '-loglevel',
      'panic',
      '-movflags',
      '+faststart',
      '-c:v',
      'copy',
      '-strict',
      '-2',
      '-q:a',
      '100',
      config.srcDirectory + '/' + dstFile
    ];
  }

  if (!dstFile) {
    printErrorMsg('Failed to convert ' + srcFile);

    return ;
  }

  printMsg('Converting ' + srcFile + ' into ' + dstFile);

  var convertProcess = childProcess.spawnSync('ffmpeg', spawnArguments);

  if (convertProcess.status != 0) {
    printErrorMsg('Failed to convert ' + srcFile);

    if (convertProcess.error) {
      printErrorMsg(convertProcess.error.toString());
    }

    return;
  }

  if (config.deleteAfter) {
    fs.unlink(config.srcDirectory + '/' + srcFile, function(err) {
      // do nothing, shit happens
    });
  } else {
    fs.rename(config.srcDirectory + '/' + srcFile, config.dstDirectory + '/' + srcFile, function(err) {
      if (err) {
        printErrorMsg(err.toString());
      }
    });
  }

  fs.rename(config.srcDirectory + '/' + dstFile, config.dstDirectory + '/' + dstFile, function(err) {
    if (err) {
      printErrorMsg(err.toString());
    }
  });
}

function mainLoop() {
  startTs = getTimestamp();

  Promise
    .try(function() {
      return getFiles();
    })
    .then(function(files) {
      if (files.length > 0) {
        printMsg(files.length + ' file(s) to convert');
        _.each(files, convertFile);
      } else {
        printMsg('No files found');
      }
    })
    .catch(function(err) {
      printErrorMsg(err);
    })
    .finally(function() {
      var seconds = startTs - getTimestamp() + config.dirScanInterval;

      if (seconds < 5) {
        seconds = 5;
      }

      printMsg('Done, will scan the folder in ' + seconds + ' second(s).');

      setTimeout(mainLoop, seconds * 1000);
    });
}

mainLoop();

**Comment by francisuk1989** [comment]
no idea if this will help out here but before this, i use to
**ffmpeg -i "streamurl" -c copy -f mp4 nameofmodel.mp4****

**Comment by forsomefun** [comment]
Does that handle the conversion?

**Comment by francisuk1989** [comment]
Yes however if a model goes private or disconnects and reconnects or offline it will just stop.

**Comment by forsomefun** [comment]
A few more questions

Can I use this as a post processing command?
Where does it out t the file?

**Comment by francisuk1989** [comment]
Can I use this as a post processing command? my kolege on this script too advanced for me, Sorry.
Where does it out t the file? Output file? it should record the MP4 inside your home folder.

**Comment by beaston02** [comment]
Hey, sorry for the slow reply. Ive been out of town for work and have had minimal access to the internet (cant have cell phones on site, and no access to computers or any electronics for that matter). 

Im not familiar with the script you posted. if youre looking to just convert a video upon completion, you should be able to set the post processing command to a script which would be the ffmpeg command you want to use to convert it. The variables you will need will be passed as explained in the config:

1 = full file path (ie: /Users/Joe/chaturbate/Female/hannah/2017/2017.07.26_19.34.47_hannah.mp4)
2 = filename (ie : 2017.07.26_19.34.47_hannah.mp4)
3 = directory (ie : /Users/Joe/chaturbate/Female/hannah/2017/)
4 = models name (ie: hannah)
5 = gender (ie: Female)

These are the "arguments" passed to the script. To try to make this more clear, what the command will do execute a script with the above arguments passed to it in that order. ie: if you have a script named "sample.sh" you could set the post processing command to "bash /path/to/sample.sh" and what the script (ChaturbateRecorder.py) would actually be executing would be:
`bash /path/to/sample.sh /Users/Joe/chaturbate/Female/hannah/2017/2017.07.26_19.34.47_hannah.mp4 2017.07.26_19.34.47_hannah.mp4 hannah Female`

Lets say you wanted to run the following command on the completed video file (I got this from a quick google search, I dont know if it would be the exact command you would want):
`ffmpeg -i infile.ts -f mp4 -vcodec libx264 -preset fast -profile:v main -acodec aac outfile.mp4 -hide_banner`

you could create a script that would be similar to:
`ffmpeg -i "$1" -f mp4 -vcodec libx264 -preset fast -profile:v main -acodec aac "$3"ENCODED-"$1" -hide_banner`

This would run the command:
`ffmpeg -i "/Users/Joe/chaturbate/Female/hannah/2017/2017.07.26_19.34.47_hannah.mp4" -f mp4 -vcodec libx264 -preset fast -profile:v main -acodec aac "/Users/Joe/chaturbate/Female/hannah/2017/"ENCODED-"2017.07.26_19.34.47_hannah.mp4" -hide_banner` 
which would convert the video file and output it to the same directory but with the prefix "ENCODED-". 

You can use other commands to manipulate the string (ie remove the file extension, which I will probably add as an option later on, but never thought about the benefit to that until I was typing this out). 

How these arguments are handled will be different in each scripting language. The example I used could be use in bash/shell (and probably other languages). In python it would be "sys.argv[#]" where "#" is the number assigned to each value above. From a quick google search, in windows it seems to be %# but I have never used batch scripts, and I have not tested this. 

You could create a sample script which just writes each argument to a file, and may precede it with what it is, ie:
`@echo path %1 > test.txt`
or whatever the proper code would be in windows (you will need to google this, because I dont know windows at all. if youre using a unix system, I can be more help). 

Because the command is ran with all the data right in the line, if you tried to run an ffmpeg command directly, it would not work because it will not interpret the arguments but instead would look something like:
`ffmpeg -i "$1" -f mp4 -vcodec libx264 -preset fast -profile:v main -acodec aac "$3"ENCODED-"$1" -hide_banner /Users/Joe/chaturbate/Female/hannah/2017/2017.07.26_19.34.47_hannah.mp4 2017.07.26_19.34.47_hannah.mp4 hannah Female` 

I hope this makes things more clear. I have not tested the post processing command in windows (and I have not heard any windows users feedback on it), but I do believe it should be compatible with windows also.
