### ISSUE TITLE
Newbie help

### ISSUE THREAD

**Issue by creampeaches** [beaston02/ChaturbateRecorder#3]
I apologise if I am spamming but have no other idea where to post this.
Thanks for investing the time into this app; however I haven't been able to use it yet:

Using a MAC
Followed the README instructions exactly but when I click ChaturbateRecorder.py, nothing happens; just about 145 lines of text.

I am using the latest version of python (python-3.5.2-macosx10.6)
Installed the required modules
Using latest pip (9.01)

Edited config file: so wishlist is set to wanted.txt in my main user directory, same for save
checkInterval is 20
genders I have kept as default

wanted I have just put the names of the models; so if 2 of the models i want to record are called: latina123 and latina 456 i have written them in the blank document as:
latina123
latina456

and as I mentioned when i click ChaturbateRecorder.py to run the app, nothing happens but the  145 lines of text

Any help or even walkthrough would be greatly appreciated

**Comment by beaston02** [comment]
The script is not meant to be launched by double clicking on it, but rather ran with terminal. Open up spotlight (command + (space bar)) and type "terminal" 

that will open up a new terminal window, which is where you can enter command lines. You will want to get to the directory containing the script (where you downloaded it to). There is two ways to do this. One is by typing "cd /path/to/script" (without quotes), or the other way, which may be easier for a beginner, is to type "cd " and then in finder, you can open the directory containing the script, and drag the icon at the top middle of the window (the blue folder with the directory name next to it) to the terminal window and drop it there. This will enter the path to that folder into the terminal window so you will now have the "cd /path/to/script" (without quotes) in the terminal, and hit return. 

Now you will just type "python3.5 ChaturbateRecorder.py" (again without quotes) and hit return. This will run the script. There should only be a couple of lines of output which will be refreshed to reflect the current status. 

Just an FYI, there has been some issues with the script opening too many files (url calls, not actual files). It eventually forces the script to quit. I have not ran into this on my mac, so you may not have the issue. Im currently looking for a solution for the problem. 

Please let me know if you have any trouble getting it running. I will leave the issue open for now

**Comment by beaston02** [comment]
Alternatively, you could drag the "ChaturbateRecorder.py" icon to the terminal and run it directly from there rather than cd-ing into the directory first. 

To do this, you would type "python3.5 " then drag the python script to the terminal window (same as you I described before, drag and drop like you were moving the file in so many other cases), and hit return. This will probably be easier as its one less step.

**Comment by creampeaches** [comment]
Got it!; I'll see if it grabs anything now. Thanks for your quick reply

**Comment by creampeaches** [comment]
Ok, so I have managed to grab a couple videos. However they only seem to be opened by VLC & nothing else, and even then they are very choppy and have no time in the scroller (00:00), therefore making it difficult to watch.. any ideas? Thank you

**Comment by creampeaches** [comment]
Is there a special way I should be closing the app when I'm done? Am I meant to be converting the files? they are all saved as .mp4

**Comment by beaston02** [comment]
You can try renaming the videos with the .ts extension. I believe that is the actual extension of the original stream. 

I changed it to .mp4 simply because I was pushing them all to the cloud, and the service I was using allowed for playing .mp4 files within the browser. 

Rename them to .ts and let me know if it helps. If so, I can make changes to the script.

**Comment by creampeaches** [comment]
Yes renaming it to .ts helps. Thank you.

One other thing it has dropped a couple times with this message:

"Exception in thread Thread-6665:i', 'peppermintpanddu', '13littlepony666']
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

It then repeats this message with all others too. Thanks so much for your effort btw!

**Comment by creampeaches** [comment]
Also; lots of the videos I am producing a very short (5-10sec) clips, and I have dozens of .ts files for a small period (like over a couple min), any idea why this is the case?
Any idea how I can merge them all for free?. Many thanks

**Comment by beaston02** [comment]
That is odd.. what are the names of the .ts files? 

How the stream actually works is, a playlist file is opened and it tells the player (in this case, the script) where the actual video is. The video on live streams isn't actually a single video, but a bunch of short clips (in chaturbates case, I believe they are 5 second clips). The stream is just one clip playing after the other. The script should be downloading them all into one file, writing each new .ts file that is downloaded at the end of the previous file, creating one large file. 



You can use ffmpeg to merge the files all into one. It is documented [here](https://trac.ffmpeg.org/wiki/Concatenate).

This will require installing ffmpeg, which you can find how to do that by googling. 

Because you yourself stated you are a newbie, and Im guessing you don't have much experience in command line, there may be some other options that may be easier. the process is called "concentrate" or "concentrating" video files. googling that may help you find an easier solution.

**Comment by beaston02** [comment]
I am closing this issue due to the original issue being solved, and no more info being reported. If the new problem of the multiple files being created is continuing, please start a new issue for that topic. Thank you!
