### ISSUE TITLE
Request: Move filename related stuff to config

### ISSUE THREAD

**Issue by Hampster82** [beaston02/ChaturbateRecorder#5]
I generally customize the filename related stuff in all your scripts a bit, so it would be great if you moved those in the separate config file as well so updating the script would be less of a hassle. Format of timestamp, whether there's a subfolder for each model or not etc.

**Comment by beaston02** [comment]
I added a setting to the config file which will allow for any of the following to be used in anyway inside the path and the filename of the recorded file:
{year}
{month}
{day} (i.e.: 26)
{hour} (in 24 hour format)
{minutes}
{seconds}
{model}
{gender}

and {path} is used for the "save_directory" path. 

For example using a made up model using the name"hannah" who is female: {path}/{gender}/{model}/{year}/{year}.{month}.{day}_{hour}.{minutes}.{seconds}_{model}.mp4  will create a file with the path "/Users/Joe/chaturbate/Female/hannah/2017/2017.07.26_19.34.47_hannah.mp4"


I hope this is what you were looking for

**Comment by mikeyside** [comment]
Hey,

Does the script have any way of telling whether a file is no longer being appended to?

I would like files to be moved to a completed folder once finished. 

And a working directly for files currently recording.

This would make Rclone much easier as Rclone using min age params seems to have some issues.

**Comment by Hampster82** [comment]
> I hope this is what you were looking for

This is exactly what I was after, thanks.

**Comment by beaston02** [comment]
@mikeyside, I can add a working directory, and completed directory. 

I was toying with the idea of a "post processing" option also, which could call custom scripts written by the user (Python, bash, she'll, batch, whatever...) this would make it so the script itself could handle the rclone copying/moving, along with whatever else you may want to do with the file (create a contact sheet, convert it to another format...) 

I'll try to get either/both of these features added to it later today or tomorrow. 

@Hampster82, thank you for the suggestion!

**Comment by beaston02** [comment]
@mikeyside, I added an option in the config to move the files to a "completed" directory. I also added an option for post processing files after they are completed. I think the post processing script may be best for what you're looking to do. If you're running a unix system, below is a sample script you could use to copy the video to google drive configured in rclone as "googledrive", then move it to a completed directory. 

`rclone copy "$1" googledrive:/chaturbate/$4;
mv "$1" "/path/to/completed/directory/$4" 
`
This would copy the file to googledrive with the path"chaturbate/<models name>/<filename>
also, I would use a new line instead of ";" between the two commands, but for some reason, it doesn't want to do a line break on here even though I put one there. 

The different parameters passed to the post processing script are listed in the config file.
 
I have not done extensive testing of the post processing script. I have simply just echoed info into a file, but it all seems to be working just fine.
